baseURL: https://lauryngore.github.io

languageCode: en-us
title: "Lauryn Gore"
theme: "toha"

# Manage languages
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true

# Site parameters
params:
  background: "images/background.jpg"
  gitRepo: https://github.com/LaurynGore/lauryngore.github.io
  gitBranch: main
  enableBlogPost: false
  enableTOC: false
  showFlags: true
  newsletter:
    enable: false
